- name: rm zookeeper home
  file: path={{ zookeeper_home }} state=absent
  when: cleanup

- name: download zookeeper tarball
  copy:
    src: "{{ files_dir }}/{{ zookeeper_tarball }}"
    dest: "{{ home }}/{{ zookeeper_tarball }}"
    force: no
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
  when: packaging == "tarball"

- name: extract zookeeper tarball
  unarchive: 
    src: "{{ home }}/{{ zookeeper_tarball }}"
    dest: "{{ home }}"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
  when: packaging == "tarball"

- name: create zookeeper cfg file
  template: src=zoo.cfg dest={{ zookeeper_confdir }}/zoo.cfg owner={{ user }} group={{ user }}

- name: rm zookeeper data directory
  file: path={{ zookeeper_datadir }} state=absent
  when: cleanup

- name: create zookeeper data directory
  file: path={{ zookeeper_datadir }} owner={{ user }} group={{ user }} state=directory

- name: create zookeeper myid file
  template: src=myid dest={{ zookeeper_datadir }}/myid owner={{ user }} group={{ user }}
