- name: rm hbase home
  file: path={{ hbase_home }} state=absent

- name: download hbase tarball
  copy:
    src: "{{ files_dir }}/{{ hbase_tarball }}"
    dest: "{{ home }}/{{ hbase_tarball }}"
    force: no
    owner: "{{ hbase_user }}"
    group: "{{ hbase_user }}"
  when: packaging == "tarball"

- name: extract hbase tarball
  unarchive: 
    src: "{{ home }}/{{ hbase_tarball }}"
    dest: "{{ home }}"
    creates: "{{ hbase_home }}"
    owner: "{{ hbase_user }}"
    group: "{{ hbase_user }}"
  when: packaging == "tarball"

- name: chown hbase home 
  file: path={{ hbase_home }} owner={{ hbase_user }} group={{ hbase_user }} recurse=true
  when: packaging == "tarball"

- name: remove hbase package
  package: name=hbase state=present state=absent
  when: packaging == "rpm"

- name: install hbase package
  package: name=hbase state=present
  when: packaging == "rpm"

- name: create hbase hbase-site.xml
  template:
    src: "hbase-site.xml"
    dest: "{{ hbase_confdir }}/hbase-site.xml"
    owner: "{{ hbase_user }}"
    group: "{{ hbase_user }}"
  tags:
  - configuration

- name: create hbase hbase-env.sh
  template:
    src: "hbase-env.sh"
    dest: "{{ hbase_confdir }}/hbase-env.sh"
    owner: "{{ hbase_user }}"
    group: "{{ hbase_user }}"
  tags:
  - configuration
