- name: create user to run benchmark
  user: name={{ user }}

- name: create hosts file
  file: src={{ files_dir }}/hosts path=/etc/hosts owner=root group=root mode=0644

- name: create ssh user config directory
  file: path=/home/{{ user }}/.ssh state=directory owner={{ user }} group={{ user }} mode=0700

- name: create ssh user config file
  copy: src=config dest=/home/{{ user }}/.ssh/config owner={{ user }} group={{ user }} mode=0600

- name: create ssh user key file
  copy: src={{ files_dir }}/id-rsa-bench dest=/home/{{ user }}/.ssh/id_rsa owner={{ user }} group={{ user }} mode=0600

- name: create ssh user authorized_keys file
  copy: src={{ files_dir }}/authorized_keys dest=/home/{{ user }}/.ssh/authorized_keys owner={{ user }} group={{ user }} mode=0600

- name: download hadoop tarball
  copy: src={{ files_dir }}/{{ tarball }} dest=/home/{{ user }}/{{ tarball }}

- name: set owner of hadoop tarball
  file: path=/home/{{ user }}/{{ tarball }} owner={{ user }} group={{ user }}

- name: extract hadoop tarball
  command: tar xf /home/{{ user }}/{{ tarball }}
  args:
    chdir: /home/{{ user }}
    creates: "{{ hadoop_home }}"

- name: set owner and group of hadoopp files
  file: path={{ hadoop_home }} owner={{ user }} group={{ user }} recurse=true

- name: create hadoop core-site.xml
  template: src=core-site.xml dest={{ hadoop_home }}/etc/hadoop/core-site.xml owner={{ user }} group={{ user }}

- name: create hadoop hdfs-site.xml
  template: src=hdfs-site.xml dest={{ hadoop_home }}/etc/hadoop/hdfs-site.xml owner={{ user }} group={{ user }}

- name: create hadoop yarn-site.xml
  template: src=yarn-site.xml dest={{ hadoop_home }}/etc/hadoop/yarn-site.xml owner={{ user }} group={{ user }}

- name: create hadoop mapred-site.xml
  template: src=mapred-site.xml dest={{ hadoop_home }}/etc/hadoop/mapred-site.xml owner={{ user }} group={{ user }}

- name: create hadoop hadoop-env.sh
  template: src=hadoop-env.sh dest={{ hadoop_home }}/etc/hadoop/hadoop-env.sh owner={{ user }} group={{ user }}
