- hosts:
  - quorum
  tasks:
  - name: start zookeeper daemon
    command: "{{ zookeeper_home }}/bin/zkServer.sh start"

- hosts:
  - master1
  - master2
  - master3
  tasks:
  - name: start journalnode daemon
    command: "{{ hadoop_home }}/sbin/hadoop-daemon.sh start journalnode"

- hosts:
  - master1
  tasks:
  - name: wait for journal nodes starting up
    pause: seconds=60
  - name: format hdfs filesystem
    command: "{{ hadoop_home }}/bin/hdfs namenode -format -force -nonInteractive"
  - name: format znode for zkfc
    command: "{{ hadoop_home }}/bin/hdfs zkfc -formatZK -force -nonInteractive"
  - name: start namenode daemon
    command: "{{ hadoop_home }}/sbin/hadoop-daemon.sh start namenode"
  - name: start zkfc daemon
    command: "{{ hadoop_home }}/sbin/hadoop-daemon.sh start zkfc"

- hosts:
  - master1
  tasks:
  - name: create tmpdir
    command: "{{ hadoop_home }}/bin/hdfs dfs -mkdir -p /tmp"
  - name: set permission to tmpdir
    command: "{{ hadoop_home }}/bin/hdfs dfs -chmod 777 /tmp"
  - name: create hbase rootdir
    command: "{{ hadoop_home }}/bin/hdfs dfs -mkdir -p /hbase"
  - name: chown hbase rootdir
    command: "{{ hadoop_home }}/bin/hdfs dfs -chown hbase:hbase /hbase"

- hosts:
  - master3
  tasks:
  - name: bootstrap hdfs standby namenode
    command: "{{ hadoop_home }}/bin/hdfs namenode -bootstrapStandby -force -nonInteractive"

- hosts:
  - master1
  tasks:
  - name: stop zkfc daemon
    command: "{{ hadoop_home }}/sbin/hadoop-daemon.sh stop zkfc"
  - name: stop namenode daemon
    command: "{{ hadoop_home }}/sbin/hadoop-daemon.sh stop namenode"

- hosts:
  - master1
  - master2
  - master3
  tasks:
  - name: stop journalnode daemon
    command: "{{ hadoop_home }}/sbin/hadoop-daemon.sh stop journalnode"

- hosts:
  - quorum
  tasks:
  - name: stop zookeeper daemon
    command: "{{ zookeeper_home }}/bin/zkServer.sh stop"
