- hosts:
  - quorum
  become: true
  tasks:
  - name: init zookeeper data dir
    command: "service zookeeper-server init --force"

- hosts:
  - quorum
  become: true
  tasks:
  - name: start zookeeper daemon
    service: name=zookeeper-server state=started

- hosts:
  - master1
  - master2
  - master3
  become: true
  tasks:
  - name: start journalnode daemon
    service: name=hadoop-hdfs-journalnode state=started

- hosts:
  - master1
  become: true
  become_user: "hdfs"
  tasks:
  - name: wait for journal nodes starting up
    pause: seconds=60
  - name: format hdfs filesystem
    command: "hdfs namenode -format -force -nonInteractive"
  - name: format znode for zkfc
    command: "hdfs zkfc -formatZK -force -nonInteractive"

- hosts:
  - master1
  become: true
  tasks:
  - name: start namenode daemon
    service: name=hadoop-hdfs-namenode state=started

- hosts:
  - master3
  become: true
  become_user: "hdfs"
  tasks:
  - name: bootstrap hdfs standby namenode
    command: "hdfs namenode -bootstrapStandby -force -nonInteractive"

- hosts:
  - master1
  become: true
  tasks:
  - name: stop namenode daemon
    service: name=hadoop-hdfs-namenode state=stopped

- hosts:
  - master1
  - master2
  - master3
  become: true
  tasks:
  - name: stop journalnode daemon
    service: name=hadoop-hdfs-journalnode state=stopped

- hosts:
  - quorum
  become: true
  tasks:
  - name: stop zookeeper daemon
    service: name=zookeeper-server state=stopped
