- hosts:
  - quorum
  become: true
  tasks:
  - name: start zookeeper daemon
    service: name=zookeeper-server state=started

- hosts:
  - master1
  - master2
  - master3
  become: true
  tasks:
  - name: start journalnode daemon
    service: name=hadoop-hdfs-journalnode state=started

- hosts:
  - master1
  become: true
  tasks:
  - name: start namenode daemon
    service: name=hadoop-hdfs-namenode state=started
  - name: start hdfs zkfc daemon
    service: name=hadoop-hdfs-zkfc state=started

- hosts:
  - master2
  become: true
  tasks:
  - name: start resourcemanager daemon
    service: name=hadoop-yarn-resourcemanager state=started
  - name: wait for resourcemanager starting up
    pause: seconds=10

- hosts:
  - master3
  become: true
  tasks:
  - name: start namenode daemon
    service: name=hadoop-hdfs-namenode state=started
  - name: start hdfs zkfc daemon
    service: name=hadoop-hdfs-zkfc state=started
  - name: start resourcemanager daemon
    service: name=hadoop-yarn-resourcemanager state=started
#  - name: start historyserver daemon
#    service: name=hadoop-mapreduce-historyserver state=started

- hosts:
  - slaves
  become: true
  tasks:
  - name: start datanode daemon
    service: name=hadoop-hdfs-datanode state=started
  - name: start nodemanager daemon
    service: name=hadoop-yarn-nodemanager state=started

#- hosts:
#  - master1
#  - master2
#  - master3
#  become: true
#  tasks:
#  - name: start hmaster daemon
#    service: name=hbase-master state=started
#
#- hosts:
#  - slaves
#  become: true
#  tasks:
#  - name: start regionserver daemon
#    service: name=hbase-regionserver state=started
