- hosts:
  - quorum
  tasks:
  - name: start zookeeper daemon
    command: "{{ zookeeper_home }}/bin/zkServer.sh start"
    args:
      chdir: "{{ zookeeper_home }}"

- hosts:
  - master1
  - master2
  - master3
  tasks:
  - name: start journalnode daemon
    command: "{{ hadoop_home }}/sbin/hadoop-daemon.sh start journalnode"

- hosts:
  - master1
  tasks:
  - name: start namenode daemon
    command: "{{ hadoop_home }}/sbin/hadoop-daemon.sh start namenode"
  - name: start hdfs zkfc daemon
    command: "{{ hadoop_home }}/sbin/hadoop-daemon.sh start zkfc"

- hosts:
  - master2
  tasks:
  - name: start resourcemanager daemon
    command: "{{ hadoop_home }}/sbin/yarn-daemon.sh start resourcemanager"
  - name: wait for resourcemanager starting up
    pause: seconds=10

- hosts:
  - master3
  tasks:
  - name: start namenode daemon
    command: "{{ hadoop_home }}/sbin/hadoop-daemon.sh start namenode"
  - name: start hdfs zkfc daemon
    command: "{{ hadoop_home }}/sbin/hadoop-daemon.sh start zkfc"
  - name: start resourcemanager daemon
    command: "{{ hadoop_home }}/sbin/yarn-daemon.sh start resourcemanager"

- hosts:
  - slaves
  tasks:
  - name: start datanode daemon
    command: "{{ hadoop_home }}/sbin/hadoop-daemon.sh start datanode"
  - name: start nodemanager daemon
    command: "{{ hadoop_home }}/sbin/yarn-daemon.sh start nodemanager"

- hosts:
  - master1
  - master2
  - master3
  tasks:
  - name: start hmaster daemon
    command: "nohup {{ hbase_home }}/bin/hbase-daemon.sh start master"
    args:
      chdir: "{{ hbase_home }}"
  tags:
  - hbase

- hosts:
  - slaves
  tasks:
  - name: start regionserver daemon
    command: "nohup {{ hbase_home }}/bin/hbase-daemon.sh start regionserver"
    args:
      chdir: "{{ hbase_home }}"
  tags:
  - hbase
