- hosts:
  - quorum
  remote_user: "{{ user }}"
  become: yes
  tasks:
  - name: start zookeeper daemon
    service: name=zookeeper-server state=started

#- hosts:
#  - master1
#  - master2
#  - master3
#  remote_user: "{{ user }}"
#  tasks:
#  - name: start journalnode daemon
#    command: "{{ hadoop_home }}/sbin/hadoop-daemon.sh start journalnode"
#    when: ha
#
#- hosts:
#  - master1
#  remote_user: "{{ user }}"
#  tasks:
#  - name: start namenode daemon
#    command: "{{ hadoop_home }}/sbin/hadoop-daemon.sh start namenode"
#  - name: start hdfs zkfc daemon
#    command: "{{ hadoop_home }}/sbin/hadoop-daemon.sh start zkfc"
#    when: ha
#
#- hosts:
#  - master2
#  remote_user: "{{ user }}"
#  tasks:
#  - name: start resourcemanager daemon
#    command: "{{ hadoop_home }}/sbin/yarn-daemon.sh start resourcemanager"
#  - name: wait for resourcemanager starting up
#    pause: seconds=10
#
#- hosts:
#  - master3
#  remote_user: "{{ user }}"
#  tasks:
#  - name: start namenode daemon
#    command: "{{ hadoop_home }}/sbin/hadoop-daemon.sh start namenode"
#    when: ha
#  - name: start hdfs zkfc daemon
#    command: "{{ hadoop_home }}/sbin/hadoop-daemon.sh start zkfc"
#    when: ha
#  - name: start resourcemanager daemon
#    command: "{{ hadoop_home }}/sbin/yarn-daemon.sh start resourcemanager"
#    when: ha
#
#- hosts:
#  - slaves
#  remote_user: "{{ user }}"
#  tasks:
#  - name: start datanode daemon
#    command: "{{ hadoop_home }}/sbin/hadoop-daemon.sh start datanode"
#  - name: start nodemanager daemon
#    command: "{{ hadoop_home }}/sbin/yarn-daemon.sh start nodemanager"
#
#- hosts:
#  - master1
#  - master2
#  - master3
#  remote_user: "{{ user }}"
#  tasks:
#  - name: start hmaster daemon
#    command: "{{ hbase_home }}/bin/hbase-daemon.sh start master"
#    args:
#      chdir: "{{ hbase_home }}"
#
#- hosts:
#  - slaves
#  remote_user: "{{ user }}"
#  tasks:
#  - name: start regionserver daemon
#    command: "{{ hbase_home }}/bin/hbase-daemon.sh start regionserver"
#    args:
#      chdir: "{{ hbase_home }}"
