- hosts:
  - slaves
  become: true
  tasks:
#  - name: stop regionserver daemon
#    service: name=hbase-regionserver state=stopped
#    ignore_errors: yes
  - name: stop nodemanager daemon
    service: name=hadoop-yarn-nodemanager state=stopped
    ignore_errors: yes
  - name: stop datanode daemon
    service: name=hadoop-hdfs-datandoe state=stopped
    ignore_errors: yes

#- hosts:
#  - master1
#  - master2
#  - master3
#  become: true
#  tasks:
#  - name: stop hmaster daemon
#    service: name=hbase-master state=stopped
#    ignore_errors: yes

- hosts:
  - master3
  become: true
  tasks:
  - name: stop resourcemanager daemon
    service: name=hadoop-yarn-resourcemanager state=stopped
    ignore_errors: yes
  - name: stop zkfc daemon
    service: name=hadoop-hdfs-zkfc state=stopped
    ignore_errors: yes
  - name: stop namenode daemon
    service: name=hadoop-hdfs-namenode state=stopped
    ignore_errors: yes

- hosts:
  - master2
  become: true
  tasks:
  - name: stop resourcemanager daemon
    service: name=hadoop-yarn-resourcemanager state=stopped
    ignore_errors: yes

- hosts:
  - master1
  become: true
  tasks:
  - name: stop zkfc daemon
    service: name=hadoop-hdfs-zkfc state=stopped
    ignore_errors: yes
  - name: stop namenode daemon
    service: name=hadoop-hdfs-namenode state=stopped
    ignore_errors: yes

- hosts:
  - master1
  - master2
  - master3
  become: true
  tasks:
  - name: stop journalnode daemon
    service: name=hadoop-hdfs-journalnode state=stopped
    ignore_errors: yes

- hosts:
  - quorum
  become: true
  tasks:
  - name: stop zookeeper daemon
    service: name=zookeeper-server state=stopped
