#- hosts:
#  - slaves
#  remote_user: "{{ user }}"
#  tasks:
#  - name: stop regionserver daemon
#    command: "{{ hbase_home }}/bin/hbase-daemon.sh stop regionserver"
#    args:
#      chdir: "{{ hbase_home }}"
#    ignore_errors: yes
#  - name: stop nodemanager daemon
#    command: "{{ hadoop_home }}/sbin/yarn-daemon.sh stop nodemanager"
#    ignore_errors: yes
#  - name: stop datanode daemon
#    command: "{{ hadoop_home }}/sbin/hadoop-daemon.sh stop datanode"
#    ignore_errors: yes
#
#- hosts:
#  - master1
#  - master2
#  - master3
#  remote_user: "{{ user }}"
#  tasks:
#  - name: stop hmaster daemon
#    command: "{{ hbase_home }}/bin/hbase-daemon.sh stop master"
#    args:
#      chdir: "{{ hbase_home }}"
#    ignore_errors: yes
#
#- hosts:
#  - master3
#  remote_user: "{{ user }}"
#  tasks:
#  - name: stop resourcemanager daemon
#    command: "{{ hadoop_home }}/sbin/yarn-daemon.sh stop resourcemanager"
#    ignore_errors: yes
#  - name: stop zkfc daemon
#    command: "{{ hadoop_home }}/sbin/hadoop-daemon.sh stop zkfc"
#    ignore_errors: yes
#  - name: stop namenode daemon
#    command: "{{ hadoop_home }}/sbin/hadoop-daemon.sh stop namenode"
#    ignore_errors: yes
#
#- hosts:
#  - master2
#  remote_user: "{{ user }}"
#  tasks:
#  - name: stop resourcemanager daemon
#    command: "{{ hadoop_home }}/sbin/yarn-daemon.sh stop resourcemanager"
#    ignore_errors: yes
#
#- hosts:
#  - master1
#  remote_user: "{{ user }}"
#  tasks:
#  - name: stop zkfc daemon
#    command: "{{ hadoop_home }}/sbin/hadoop-daemon.sh stop zkfc"
#    ignore_errors: yes
#  - name: stop namenode daemon
#    command: "{{ hadoop_home }}/sbin/hadoop-daemon.sh stop namenode"
#    ignore_errors: yes
#
#- hosts:
#  - master1
#  - master2
#  - master3
#  remote_user: "{{ user }}"
#  tasks:
#  - name: stop journalnode daemon
#    command: "{{ hadoop_home }}/sbin/hadoop-daemon.sh stop journalnode"
#    ignore_errors: yes
#
#- hosts:
#  - quorum
#  remote_user: "{{ user }}"
#  tasks:
#  - name: stop zookeeper daemon
#    command: "{{ zookeeper_home }}/bin/zkServer.sh stop"
#    args:
#      chdir: "{{ zookeeper_home }}"
#    ignore_errors: yes

- hosts:
  - quorum
  become: yes
  tasks:
  - name: stop zookeeper daemon
    service: name=zookeeper-server state=stopped
