- name: rm name dir
  file: path={{ dfs_namenode_name_dir }} state=absent
  when: cleanup

- name: rm jn edits dir
  file: path={{ dfs_journalnode_edits_dir }} state=absent
  when: cleanup

- name: rm data dir 1
  file: path={{ data_dir_1 }} state=absent
  when: cleanup

- name: rm data dir 2
  file: path={{ data_dir_2 }} state=absent
  when: cleanup

- name: rm hadoop home
  file: path={{ hadoop_home }} state=absent
  when: cleanup

- name: download hadoop tarball
  copy:
    src: "{{ files_dir }}/{{ hadoop_tarball }}"
    dest: "{{ home }}/{{ hadoop_tarball }}"
    force: no
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"
  when: packaging == "tarball"

- name: extract hadoop tarball
  unarchive: 
    src: "{{ home }}/{{ hadoop_tarball }}"
    dest: "{{ home }}"
    creates: "{{ hadoop_home }}"
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"
  when: packaging == "tarball"

- name: remove hadoop-package
  package: name=hadoop state=present state=absent
  when: cleanup and packaging == "rpm"

- name: install hadoop-package
  package: name=hadoop state=present
  when: packaging == "rpm"

- name: create hadoop core-site.xml
  template:
    src: "core-site.xml"
    dest: "{{ hadoop_confdir }}/core-site.xml"
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"

- name: create hadoop hdfs-site.xml
  template:
    src: "hdfs-site.xml"
    dest: "{{ hadoop_confdir }}/hdfs-site.xml"
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"

- name: create hadoop yarn-site.xml
  template:
    src: "yarn-site.xml"
    dest: "{{ hadoop_confdir }}/yarn-site.xml"
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"

- name: create hadoop mapred-site.xml
  template:
    src: "mapred-site.xml"
    dest: "{{ hadoop_confdir }}/mapred-site.xml"
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"

- name: create hadoop hadoop-env.sh
  template:
    src: "hadoop-env.sh"
    dest: "{{ hadoop_confdir }}/hadoop-env.sh"
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"

- name: download hadoop native library
  copy:
    src: "{{ files_dir }}/libhadoop.so"
    dest: "{{ hadoop_home }}/lib/native/"
    force: no
    mode: "0755"
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"
  when: packaging == "tarball"

