- name: remove require tty
  lineinfile: regexp="^Defaults\s+requiretty" dest=/etc/sudoers state=absent
  tags:
  - configuration

- name: create hosts file
  template: src=hosts dest=/etc/hosts owner=root group=root
  tags:
  - configuration

- name: install libselinux-python package
  package: name=libselinux-python state=present
  when: packaging == "rpm"

- name: disable selinux
  selinux: state=disabled

- name: disable iptables
  service: name=iptables enabled=no state=stopped

- name: create ssh user config directory
  file: path={{ home }}/.ssh state=directory owner={{ user }} group={{ user }} mode=0700
  tags:
  - configuration

- name: create ssh user config file
  copy: src=config dest={{ home }}/.ssh/config owner={{ user }} group={{ user }} mode=0600
  tags:
  - configuration

- name: install jdk
  package: name={{ java_package }} state=present

- name: get cdh repository location
  get_url: url=https://archive.cloudera.com/cdh5/redhat/6/x86_64/cdh/cloudera-cdh5.repo dest=/etc/yum.repos.d/
  when: packaging == "rpm"

#- name: create user to run benchmark
#  user: name={{ user }}
#
#- name: create ssh user key file
#  copy: src={{ files_dir }}/id-rsa-bench dest={{ home }}/.ssh/id_rsa owner={{ user }} group={{ user }} mode=0600
#
#- name: create ssh user authorized_keys file
#  copy: src={{ files_dir }}/authorized_keys dest={{ home }}/.ssh/authorized_keys owner={{ user }} group={{ user }} mode=0600
