- name: create hosts file
  template: src=hosts dest=/etc/hosts owner=root group=root
  become: yes

- name: disable selinux
  selinux: state=disabled
  become: yes

- name: disable iptables
  service: name=iptables enabled=no state=stopped
  become: yes

- name: create ssh user config directory
  file: path={{ home }}/.ssh state=directory owner={{ user }} group={{ user }} mode=0700

- name: create ssh user config file
  copy: src=config dest={{ home }}/.ssh/config owner={{ user }} group={{ user }} mode=0600

- name: install jdk
  package: name={{ java_package }} state=present
  become: yes

#- name: create user to run benchmark
#  user: name={{ user }}
#
#- name: create ssh user key file
#  copy: src={{ files_dir }}/id-rsa-bench dest={{ home }}/.ssh/id_rsa owner={{ user }} group={{ user }} mode=0600
#
#- name: create ssh user authorized_keys file
#  copy: src={{ files_dir }}/authorized_keys dest={{ home }}/.ssh/authorized_keys owner={{ user }} group={{ user }} mode=0600
